### ISSUE TITLE
Shamrock语音视频测试。回:该消息类型暂不支持查看

### ISSUE THREAD

**Issue by qpdbzzz** [Zyy955/Lain-plugin#4]
该消息类型暂不支持查看

![Screenshot_2023-11-03-04-20-34-17_e9df68518e6a1ad3b48efd890143f295.jpg](https://github.com/Zyy955/Lain-plugin/assets/145204697/2f0ae7cf-14cf-48fa-b21b-a31cfaafac11)

![Screenshot_2023-11-03-04-21-57-91_e9df68518e6a1ad3b48efd890143f295.jpg](https://github.com/Zyy955/Lain-plugin/assets/145204697/20ef4c2c-8649-4640-ac48-e75610ab2229)

![Screenshot_2023-11-03-04-22-07-84_e9df68518e6a1ad3b48efd890143f295.jpg](https://github.com/Zyy955/Lain-plugin/assets/145204697/f23d3372-5c89-430f-ad90-bd72e6fb28e4)

语音报错复制
04:19:18] ERROR java.io.FileNotFoundException: 目标文件不存在
	at moe.fuqiuluo.shamrock.utils.MD5.genFileMd5Hex(Native Method)
	at moe.fuqiuluo.qqinterface.servlet.transfile.FileTransfer.transTroopResource(FileTransfer.kt:62)
	at moe.fuqiuluo.qqinterface.servlet.transfile.Transfer.uploadGroupVoice(Transfer.kt:75)
	at moe.fuqiuluo.qqinterface.servlet.transfile.Transfer.uploadGroupVoice$default(Transfer.kt:70)
	at moe.fuqiuluo.qqinterface.servlet.transfile.Transfer$ROUTE$2.invokeSuspend(Transfer.kt:14)
	at moe.fuqiuluo.qqinterface.servlet.transfile.Transfer$ROUTE$2.invoke(Unknown Source:11)
	at moe.fuqiuluo.qqinterface.servlet.transfile.Transfer$ROUTE$2.invoke(Unknown Source:6)
	at moe.fuqiuluo.qqinterface.servlet.transfile.TransferKt.trans(Transfer.kt:115)
	at moe.fuqiuluo.qqinterface.servlet.msg.MessageMaker.createRecordElem-yxL6bBk(MessageMaker.kt:583)
	at moe.fuqiuluo.qqinterface.servlet.msg.MessageMaker.access$createRecordElem-yxL6bBk(MessageMaker.kt:73)
	at moe.fuqiuluo.qqinterface.servlet.msg.MessageMaker$createRecordElem$1.invokeSuspend(Unknown Source:19)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

![Screenshot_2023-11-03-04-25-13-47_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://github.com/Zyy955/Lain-plugin/assets/145204697/fc0147ec-129a-4b8b-8532-c1e08be70d9a)

![Screenshot_2023-11-03-04-25-20-03_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://github.com/Zyy955/Lain-plugin/assets/145204697/8316f23c-44a5-4497-afdf-f2ec4ff13ad6)

**Comment by Zyy955** [comment]
你的shamrock跟喵崽都不在一个系统内，如何使用本地文件发送
