### ISSUE TITLE
QQ机器人代理问题

### ISSUE THREAD

**Issue by mkroen** [Zyy955/Lain-plugin#44]
由于QQ机器人需要设置ip白名单，我本地的香橙派没有公网ip，因此使用vps的ip作为代理，但设置全局代理后，会报如下的错：
```
[ERROR] createSession:  AxiosError: Client network socket disconnected before secure TLS connection was established
    at AxiosError.from (/home/orangepi/github/yz/Miao-Yunzai/node_modules/.pnpm/axios@1.6.7/node_modules/axios/dist/node/axios.cjs:837:14)
    at RedirectableRequest.handleRequestError (/home/orangepi/github/yz/Miao-Yunzai/node_modules/.pnpm/axios@1.6.7/node_modules/axios/dist/node/axios.cjs:3087:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (/home/orangepi/github/yz/Miao-Yunzai/node_modules/.pnpm/follow-redirects@1.15.5_debug@4.3.4/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/home/orangepi/github/yz/Miao-Yunzai/node_modules/.pnpm/axios@1.6.7/node_modules/axios/dist/node/axios.cjs:3877:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  localAddress: undefined,
  port: '7890',
  host: '127.0.0.1',
```
这里看起来是代理的问题，但我做了相关尝试认为不是，因为
```
curl --location 'https://bots.qq.com/app/getAppAccessToken' ***
curl --location 'https://api.sgroup.qq.com/users/@me' ***
```
这些接口都是能成功返回的，关闭代理显示ip不在白名单，开启能成功获取token和user信息

做了相关的搜索之后，感觉这一篇文章比较符合我的情况：
[https://segmentfault.com/a/1190000039412894](url)
我怀疑是这里请求的时候检测到了本地的代理，导致直接报错了

但由于我不是很懂前端，没能找到类似的方法添加这个参数，希望能解决代理问题或者给我指指路

**Comment by Zyy955** [comment]
你的意思是想要请求的时候可以配置代理对吧？

**Comment by mkroen** [comment]
> 你的意思是想要请求的时候可以配置代理对吧？

我是直接上全局代理会报错，加上代理配置也挺好，能解决问题就行

**Comment by mkroen** [comment]
发现是qq-group-bot这个依赖包里创建的axios对象，项目里只有对依赖包的调用，可能没法适配代理问题。
我的解决方法如下：
目录为qq-group-bot/lib/qqBot.js文件的42行，我在这里对代理进行配置，能成功解决报错问题了。
```
// 在class外添加 代理设置
const tunnel = require('tunnel');
const agent = tunnel.httpsOverHttp({
    proxy: {
        host: '127.0.0.1',
        port: 7890,
    }
});

// 修改axios对象创建 添加httpsAgent和proxy参数
this.request = axios_1.default.create({
    baseURL: this.config.sandbox ? 'https://sandbox.api.sgroup.qq.com' : `https://api.sgroup.qq.com`,
    timeout: config.timeout || 5000,
    headers: {
        'User-Agent': `BotNodeSDK/0.0.1`
    },
    httpsAgent: agent,
    proxy: false, // 设置axios不要自动检测命令行代理设置
});
```
