### ISSUE TITLE
Ubuntu docker环境 喵崽lain启动失败

### ISSUE THREAD

**Issue by XHLiang0** [Zyy955/Lain-plugin#48]
报错内容：
[MiaoYz][15:19:50.403][ERRO] 载入插件错误：lain-plugin
[MiaoYz][15:19:50.404][ERRO] Error: ENOENT: no such file or directory, open './plugins/Lain-plugin/package.json'
    at Object.readFileSync (node:fs:456:20)
    at file:///root/TRSS_AllBot/Miao-Yunzai/plugins/lain-plugin/model/config.js:9:32
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async PluginsLoader.load (file:///root/TRSS_AllBot/Miao-Yunzai/lib/plugins/loader.js:61:19)
    at async Yunzai.skip_login (file:///root/TRSS_AllBot/Miao-Yunzai/lib/bot.js:37:12)
    at async Yunzai.run (file:///root/TRSS_AllBot/Miao-Yunzai/lib/bot.js:19:36)
    at async file:///root/TRSS_AllBot/Miao-Yunzai/app.js:3:1

硬件：树莓派5-8GB
安装使用的TRSS脚本完成，docker环境下异常，但是Tmoe环境运行正常，不确定是什么原因，发出来大佬帮忙看看

**Comment by XHLiang0** [comment]
![Uploading Clip_2024-02-04_15-28-21.png…]()

**Comment by XHLiang0** [comment]
![Clip_2024-02-04_15-28-21](https://github.com/Zyy955/Lain-plugin/assets/90927576/93d37346-1e21-4c1e-ae65-b9801fe6f17f)

**Comment by Zyy955** [comment]
文件夹改Lain-plugin

**Comment by XHLiang0** [comment]
可以了，谢谢大佬
