### ISSUE TITLE
bug（可能）：锅巴回复的登录指令有报错，无法正常返回信息内容

### ISSUE THREAD

**Issue by XHLiang0** [Zyy955/Lain-plugin#55]
这个问题好像不是很严重，除了需要锅巴的时候才会卡一下，倒也不着急处理

复现方法：使用锅巴登录指令时候返回登录地址时候会出现此报错，疑似也是回复信息的问题

以下为报错结果：
[MiaoYz][13:00:45.616][ERRO] 发送消息错误:[{"test":true,"message":[{"type":"node","data":{"id":1748522185}},{"type":"node","data":{"id":1461156430}},{"type":"node","data":{"id":538166287}},{"type":"node","data":{"id":1723854111}}],"data":{"type":"test","text":"forward","app":"com.tencent.multimsg","meta":{"detail":{"news":[{"text":"1"}]}...
[MiaoYz][13:00:45.616][ERRO] TypeError: Cannot read properties of undefined (reading 'msg')
    at Object.array (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/Lain-plugin/lib/common/common.js:142:44)
    at Shamrock.getShamrock (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/Lain-plugin/adapter/shamrock/index.js:1220:19)
    at Shamrock.sendReplyMsg (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/Lain-plugin/adapter/shamrock/index.js:1183:53)
    at ICQQEvent.e.reply [as replyNew] (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/Lain-plugin/adapter/shamrock/index.js:894:48)
    at e.reply (file:///root/TRSS_AllBot/Miao-Yunzai/lib/plugins/loader.js:532:28)
    at e.reply (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/yunzai-c-v-plugin/apps/%E6%B6%88%E6%81%AF%E9%A3%8E%E6%8E%A7%E5%A4%84%E7%90%86.js:31:23)
    at GuobaLogin.reply (file:///root/TRSS_AllBot/Miao-Yunzai/lib/plugins/plugin.js:71:19)
    at GuobaLogin.login (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/Guoba-Plugin/apps/login.js?1708463698572:62:17)
    at async PluginsLoader.deal (file:///root/TRSS_AllBot/Miao-Yunzai/lib/plugins/loader.js:292:52)
[MiaoYz][13:00:45.619][ERRO] [锅巴登录][login]
[MiaoYz][13:00:45.619][ERRO] undefined

Shamrock 版本: 1.0.8.r320.2c8094c
lain-plugin 版本：1.4.5（2024-02-20更新版本）
系统版本：Flyme 10.24.1.15 Daily
Android 版本: 13.0（1682851189）
LSPosed 框架版本: 1.9.2（7024）
设备的制造商和型号: MEIZU 18
设备的 CPU 架构: Snapdragon 888 (Lahaina)

**Comment by lava081** [comment]
卸载此插件file:///root/TRSS_AllBot/Miao-Yunzai/plugins/yunzai-c-v-plugin/apps/%E6%B6%88%E6%81%AF%E9%A3%8E%E6%8E%A7%E5%A4%84%E7%90%86.js:31:23
